nodeLinker: node-modules
npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAuthToken: "9FF84F5C-4B1F-4BAE-AD3A-5A06512048D0"
  awesome.me:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAuthToken: "9FF84F5C-4B1F-4BAE-AD3A-5A06512048D0"
