export const MOON_SIZE = '600px';

export const CRATER_KEYS = ['crater-1', 'crater-2', 'crater-3'] as const;

export const COMET_KEYS = [
	'comet-1',
	'comet-2',
	'comet-3',
	'comet-4',
	'comet-5',
	'comet-6',
] as const;

export const CLOUD_GROUPS = [
	{ styleKey: 'clouds-1', cloudKeys: ['c1-1', 'c1-2'] },
	{ styleKey: 'clouds-2', cloudKeys: ['c2-1', 'c2-2'] },
	{
		styleKey: 'clouds-3',
		cloudKeys: [
			'c3-1',
			'c3-2',
			'c3-3',
			'c3-4',
			'c3-5',
			'c3-6',
			'c3-7',
			'c3-8',
			'c3-9',
			'c3-10',
			'c3-11',
			'c3-12',
			'c3-13',
		],
	},
	{ styleKey: 'clouds-4', cloudKeys: ['c4-1', 'c4-2', 'c4-3'] },
	{ styleKey: 'clouds-5', cloudKeys: ['c5-1', 'c5-2'] },
] as const;

export const STARS = [
	{ id: 's1', size: 's' },
	{ id: 's2', size: 'm' },
	{ id: 's3', size: 's' },
	{ id: 's4', size: 's' },
	{ id: 's5', size: 's' },
	{ id: 's6', size: 'm' },
	{ id: 's7', size: 's' },
	{ id: 's8', size: 's' },
	{ id: 's9', size: 'm' },
	{ id: 's10', size: 's' },
	{ id: 's11', size: 'm' },
	{ id: 's12', size: 'm' },
	{ id: 's13', size: 'm' },
	{ id: 's14', size: 's' },
	{ id: 's15', size: 'm' },
	{ id: 's16', size: 's' },
	{ id: 's17', size: 's' },
	{ id: 's18', size: 'm' },
	{ id: 's19', size: 'l' },
	{ id: 's20', size: 'l' },
	{ id: 's21', size: 's' },
	{ id: 's22', size: 's' },
	{ id: 's23', size: 'm' },
	{ id: 's24', size: 'xs' },
	{ id: 's25', size: 'm' },
	{ id: 's26', size: 'xs' },
	{ id: 's27', size: 'm' },
	{ id: 's28', size: 's' },
	{ id: 's29', size: 's' },
	{ id: 's30', size: 's' },
	{ id: 's31', size: 's' },
	{ id: 's32', size: 'm' },
	{ id: 's33', size: 'm' },
	{ id: 's34', size: 'm' },
	{ id: 's35', size: 's' },
	{ id: 's36', size: 's' },
	{ id: 's37', size: 's' },
	{ id: 's38', size: 'm' },
	{ id: 's39', size: 'xs' },
	{ id: 's40', size: 'm' },
	{ id: 's41', size: 's' },
	{ id: 's42', size: 'l' },
	{ id: 's43', size: 'm' },
	{ id: 's44', size: 's' },
	{ id: 's45', size: 'm' },
	{ id: 's46', size: 'xs' },
	{ id: 's47', size: 'm' },
	{ id: 's48', size: 'm' },
	{ id: 's49', size: 's' },
	{ id: 's50', size: 's' },
] as const;
