import type { TextScale, Theme } from '../../accessibility-widget.types';

export type AccessibilitySettings = {
	textScale: TextScale;
	theme: Theme;
	lineHeightDisplayValue: string;
	letterSpacingDisplayValue: string;
	canDecreaseScale: boolean;
	canIncreaseScale: boolean;
	canDecreaseLineHeight: boolean;
	canIncreaseLineHeight: boolean;
	canDecreaseLetterSpacing: boolean;
	canIncreaseLetterSpacing: boolean;
	isThemeDefault: boolean;
	isTextScaleDefault: boolean;
	isLineHeightDefault: boolean;
	isLetterSpacingDefault: boolean;
	isAllDefault: boolean;
	selectTheme: (theme: Theme) => void;
	decreaseScale: () => void;
	increaseScale: () => void;
	decreaseLineHeight: () => void;
	increaseLineHeight: () => void;
	decreaseLetterSpacing: () => void;
	increaseLetterSpacing: () => void;
	resetTheme: () => void;
	resetTextScale: () => void;
	resetLineHeight: () => void;
	resetLetterSpacing: () => void;
	resetAll: () => void;
};
